### ISSUE TITLE
阅读Reading 无法渲染（生成）

### ISSUE THREAD

**Issue by nekomeowww** [raytaylorlin/hexo-theme-raytaylorism#54]
**同标题，即便复制了<code>./hexo-theme-raytaylorism/_md/reading</code>的所有东西到<code>./blog_root/source/</code>**               
 

下面是error
```
$ hexo s
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: C:\Files\Support\GitHub Blog\fanff0324\themes\raytaylorism\layout\reading.e                                                                     js:1
 >> 1| <% var readingData = site.data.reading;
    2|     var tabCount = Object.keys(readingData.define).length;
    3| %>
    4|

Cannot read property 'define' of undefined
    at eval (eval at <anonymous> (C:\Files\Support\GitHub Blog\fanff0324\node_modules\ejs\lib\ejs.js:242:1                                                                     4), <anonymous>:31:43)
    at eval (eval at <anonymous> (C:\Files\Support\GitHub Blog\fanff0324\node_modules\ejs\lib\ejs.js:242:1                                                                     4), <anonymous>:32:3392)
    at C:\Files\Support\GitHub Blog\fanff0324\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (C:\Files\Support\GitHub Blog\fanff0324\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (C:\Files\Support\GitHub Blog\fanff0324\node_modules\hexo\lib\theme\view.js:29:15)
    at C:\Files\Support\GitHub Blog\fanff0324\node_modules\hexo\lib\hexo\index.js:387:25
    at tryCatcher (C:\Files\Support\GitHub Blog\fanff0324\node_modules\bluebird\js\release\util.js:16:23)
    at C:\Files\Support\GitHub Blog\fanff0324\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (C:\Files\Support\GitHub Blog\fanff0324\node_modules\hexo\lib\hexo\router.js:134:                                                                     3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by raytaylorlin** [comment]
[README](https://github.com/raytaylorlin/hexo-theme-raytaylorism/blob/master/README.md)
> 复制`yourblog/themes/raytaylorism/_data`文件夹到`yourblog/source`目录下
